workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: 'KJV Bible Widgets'
    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.owenfortin.kjvbiblewidgets"
        XCODE_PROJECT: "KJV Bible Widgets.xcodeproj"
        XCODE_SCHEME: "KJV Bible Widgets"
        APP_STORE_APPLE_ID: 6806205518
      xcode: latest
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
